#!/usr/bin/env escript
%% -*- erlang -*-

-define(DEF_ENABLED_PLUGINS_FILE, "enabled_plugins").
-define(DEF_PLUGINS_DIR, "oacd_plugins").

main(["add", Name, GitRepo]) ->
	io:format("Adding ~p~n", [GitRepo]),
	Location = "oacd_plugins/" ++ Name,
	git_clone(GitRepo, Location);

main(["enable", Name]) ->
	enable_plugin(list_to_atom(Name)).

git_clone(GitRepo, Location) ->
	Command = io_lib:format("git clone ~p ~p", [GitRepo, Location]),
	io:format("~p", [os:cmd(Command)]).

enabled_plugins(File) ->
	case file:consult(File) of
		{error, enoent} ->
			[];
		{ok, [Plugins]} ->
			Plugins
	end.

write_enabled_plugins(Plugins, File) ->
	{ok, F} = file:open(File, [write]),
	Data = io_lib:format("~p.",[Plugins]),
	file:write(F, Data).

enable_plugin(Plugin) ->
	EnabledPluginsFile = ?DEF_ENABLED_PLUGINS_FILE,
	EnabledPlugins = enabled_plugins(?DEF_ENABLED_PLUGINS_FILE),
	EnabledPluginsNew = lists:usort([Plugin | EnabledPlugins]),
	write_enabled_plugins(EnabledPluginsNew, EnabledPluginsFile),
	io:format("Previously enabled plugins ~p~n", [EnabledPlugins]),
	io:format("Current enabled plugins ~p~n", [EnabledPluginsNew]),
	ok.