#!/bin/bash

BASEDIR="$( cd "$( dirname "$0" )" && pwd)"
PLUGINDIR=$BASEDIR/oacd_plugins
ENABLED_PLUGINS_FILE=$BASEDIR/enabled_plugins

ULON="\033[4m"
ULOFF="\033[0m"

add_plugin()
{
	PLUGIN=$1
	PLUGIN_REPO=$2
	PLUGIN_PATH=$PLUGINDIR/$PLUGIN
	echo "Cloning $PLUGIN from $PLUGIN_REPO into $PLUGIN_PATH"

	git clone $PLUGIN_REPO $PLUGINDIR/$PLUGIN
}

create_plugin()
{
	PLUGIN=$1
	PLUGIN_PATH=$PLUGINDIR/$PLUGIN
	echo "Creating rebar app for $PLUGIN in $PLUGIN_PATH"

	mkdir -p $PLUGIN_PATH
	cd $PLUGIN_PATH
	$BASEDIR/rebar create-app appid=$PLUGIN
}

enable_plugin()
{
	PLUGIN=$1
	echo "Enabling $PLUGIN plugin"
	echo $PLUGIN >> $ENABLED_PLUGINS_FILE
}

disable_plugin()
{
	PLUGIN=$1
	echo "Disabling $PLUGIN plugin"

	grep -v "^$PLUGIN$" $ENABLED_PLUGINS_FILE > $ENABLED_PLUGINS_FILE.tmp
	mv $ENABLED_PLUGINS_FILE.tmp $ENABLED_PLUGINS_FILE
}

usage()
{
	echo "List of commands"
	echo -e "  add-plugin ${ULON}name${ULOFF} ${ULON}git-repo${ULOFF}"
	echo -e "  create-plugin ${ULON}name${ULOFF}"
	echo -e "  disable-plugin ${ULON}name${ULOFF}"
	echo -e "  enable-plugin ${ULON}name${ULOFF}"
	echo ""
}

case $* in
    'add-plugin') add_plugin $2 $3;;
	'create-plugin') create_plugin $2;;
	'enable-plugin') enable_plugin $2;;
	'disable-plugin') disable_plugin $2;;
	*) usage;;
esac